apiVersion: v1
kind: Service
metadata:
  name: devsu-api-svc
  namespace: devsu
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: devsu-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: NodePort
